version: 2.1
orbs:
  python: circleci/python@0.1
  node: circleci/node@1.1.6
  heroku: circleci/heroku@1.0.1
  codecov: codecov/codecov@1.0.5
  slack: circleci/slack@3.4.2
  test-runner: ghostinspector/test-runner@1.0.0
jobs:
  test:
    docker:
      - image: circleci/python:3.8-node-browsers
      - image: circleci/postgres:12-alpine-postgis-ram
        environment:
          POSTGRES_USER: ubuntu
          POSTGRES_DB: circle_test
      - image: circleci/redis

    environment:
      DJANGO_SETTINGS_MODULE: sampleapp.sampleapp.settings.circleci

    working_directory: /home/circleci/project

    steps:
      - checkout

      - python/load-cache
      - run: sudo apt-get update && sudo apt-get install -y gdal-bin python-gdal python3-gdal
      - python/install-deps
      - python/save-cache
        #TODO: caching the dev requirements requires caching the bins they install as well, figure out how to do that
      - run: pip install --user -r requirements-dev.txt

      - node/with-cache:
          steps:
            - run: yarn install --frozen-lockfile
            - run: yarn add webpack
            - run: yarn run build

      - run: scripts/validate.sh
      - run: yarn run test --ci --watchAll=false --collectCoverage=true
      - run: mkdir test_reports
      - run: mv coverage test_reports/next
      - run: coverage run --source='.' manage.py test
      - store_test_results:
          path: test_reports
      - codecov/upload
      - slack/status:
          fail_only: true
          channel: "#sampleapp-internal"
          only_for_branches: develop,master
  build:
    docker:
      - image: cimg/base:2020.01
    parameters:
      environment:
        description: environment string
        type: string
        default: development
      app-name:
        description: destination app
        type: string
        default: lm-sampleapp-development
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
          version: 19.03.8

      # could probably put this into the docker image vs installing everytime
      - heroku/install
      - run: heroku container:login
      - run:
          name: Define Environment Variable at Runtime
          command: |
            export SENTRY_DSN=$(heroku config:get SENTRY_DSN)
            echo 'export SENTRY_DSN=$SENTRY_DSN' >> $BASH_ENV
            source $BASH_ENV
      - run: docker build --target web --tag registry.heroku.com/<< parameters.app-name >>/web  --build-arg ENVIRONMENT="<< parameters.environment >>" --build-arg APP_VERSION_RELEASE=$CIRCLE_SHA1 --build-arg BUILD_TIME="$(date)" --build-arg SENTRY_DSN .
      - run: docker build --target release --tag registry.heroku.com/<< parameters.app-name >>/release  --build-arg ENVIRONMENT="<< parameters.environment >>" --build-arg APP_VERSION_RELEASE=$CIRCLE_SHA1 --build-arg BUILD_TIME="$(date)" --build-arg SENTRY_DSN .
      - run: docker push registry.heroku.com/<< parameters.app-name >>/web
      - run: docker push registry.heroku.com/<< parameters.app-name >>/release
      - run: heroku container:release web release -a << parameters.app-name >>
      #- run: heroku container:push web -a << parameters.app-name >> --arg ENVIRONMENT="<< parameters.environment >>",APP_VERSION_RELEASE=$CIRCLE_SHA1,BUILD_TIME="$(date)",SERVER_BASE_URL="HTTP://127.0.0.1:8000"
          #--SENTRY_DSN
          #--arg SENTRY_AUTH_TOKEN

      - slack/status:
          channel: "#sampleapp-internal"



  # ghostinspector:
  #   docker:
  #     - image: cimg/base:2020.01
  #   steps:
  #     - test-runner/execute-suite:
  #         start-url: '<URL GOES HERE>'
  #         id: ID_GOES_HERE

workflows:
  version: 2.1
  test:
    jobs:
      # - test:
      #     context: lightmatter

      # - build:
      #     name: build-dev
      #     context: lightmatter
      #     environment: development
      #     app-name: lm-sampleapp-development
      #     requires:
      #       - test
      #     filters:
      #       branches:
      #         only: develop


      - build:
          name: build-prod
          context: lightmatter
          environment: production
          app-name: lm-sampleapp-production
          # requires:
          #   - test
          filters:
            branches:
              only: master

      # - ghostinspector:
      #     context: lightmatter
      #     requires:
      #       - deploy-dev
