#!/bin/bash
set -e
cd /app/
PID=/app/gunicorn.pid

if [ -f $PID ]; then rm $PID; fi

exec gunicorn sampleapp.sampleapp.asgi:application --bind 0.0.0.0:8000  -k uvicorn.workers.UvicornWorker --pid=$PID --access-logfile - --preload
