# Generated by Django 4.0 on 2022-01-08 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('util', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testfilemodel',
            options={'verbose_name': 'test', 'verbose_name_plural': 'tests'},
        ),
        migrations.AlterField(
            model_name='testfilemodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
